# Generated by Django 3.1.7 on 2021-03-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='username')),
                ('password', models.CharField(max_length=64, verbose_name='password')),
                ('useremail', models.CharField(max_length=128, verbose_name='email')),
                ('registered_date', models.DateTimeField(auto_now_add=True, verbose_name='registered_date')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
    ]
